# all
server:
  port: 8081

spring:
  profiles:
    active: prod
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/


logging:
  level:
    org:
      springframework:
        security: TRACE

# production
---
spring:
  profiles: prod
  jpa:
    properties:
      hibernate:
        dialect: cn.rypacker.productkeymanager.databasehelpers.sqlite.SQLiteDialect
        hbm2ddl:
          auto: update
        show_sql: false


# development
---
spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        dialect: cn.rypacker.productkeymanager.databasehelpers.sqlite.SQLiteDialect
        hbm2ddl:
          auto: create-drop
        show_sql: true
  templates:
    cache: false


