# all
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

# production
---
spring:
  profiles: prod
  # H2 database
  datasource:
    # TODO NEXT LINE WILL CAUSE EXCEPTION, fix it
    url: jdbc:h2:file:./data/record;DB_CLOSE_DELAY=-1
    username: sa
    password:



# development
---
spring:
  profiles: dev
  jpa:
    hibernate:
      dll-auto:update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/testDb
    username: admin
    password: admin

