version: "3.0"
services:
  productKeyManager4:
    image: wzxutao/pkm:240225
    container_name: product-key-manager4
    ports:
    - 8084:8084
    volumes:
    - /share/XTpro:/opt/pkm/data
    environment:
      - TZ=Asia/Shanghai

